# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateDataRsp

    CreateDataRsp(;
        object_type=nothing,
        name=nothing,
        description=nothing,
        short_id=nothing,
        created_at=nothing,
        updated_at=nothing,
        path="",
        fmt="raw",
    )

    - object_type::String
    - name::String
    - description::String
    - short_id::String
    - created_at::ZonedDateTime
    - updated_at::ZonedDateTime
    - path::String
    - fmt::String
"""
Base.@kwdef mutable struct CreateDataRsp <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    short_id::Union{Nothing, String} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    path::Union{Nothing, String} = ""
    fmt::Union{Nothing, String} = "raw"

    function CreateDataRsp(object_type, name, description, short_id, created_at, updated_at, path, fmt, )
        OpenAPI.validate_property(CreateDataRsp, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateDataRsp, Symbol("name"), name)
        OpenAPI.validate_property(CreateDataRsp, Symbol("description"), description)
        OpenAPI.validate_property(CreateDataRsp, Symbol("short_id"), short_id)
        OpenAPI.validate_property(CreateDataRsp, Symbol("created_at"), created_at)
        OpenAPI.validate_property(CreateDataRsp, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(CreateDataRsp, Symbol("path"), path)
        OpenAPI.validate_property(CreateDataRsp, Symbol("fmt"), fmt)
        return new(object_type, name, description, short_id, created_at, updated_at, path, fmt, )
    end
end # type CreateDataRsp

const _property_types_CreateDataRsp = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("short_id")=>"String", Symbol("created_at")=>"ZonedDateTime", Symbol("updated_at")=>"ZonedDateTime", Symbol("path")=>"String", Symbol("fmt")=>"String", )
OpenAPI.property_type(::Type{ CreateDataRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateDataRsp[name]))}

function check_required(o::CreateDataRsp)
    o.object_type === nothing && (return false)
    o.name === nothing && (return false)
    o.description === nothing && (return false)
    o.short_id === nothing && (return false)
    o.created_at === nothing && (return false)
    o.updated_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateDataRsp }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateDataRsp", :enum, val, ["data"])
    end





    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "CreateDataRsp", :format, val, "date-time")
    end

    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "CreateDataRsp", :format, val, "date-time")
    end


end