# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateDataReq

    CreateDataReq(;
        object_type=nothing,
        name=nothing,
        description="",
        base64_encoded=false,
        data="",
        data_uri="",
    )

    - object_type::String
    - name::String : Data name
    - description::String : Data description
    - base64_encoded::Bool : Whether the data in &#x60;data_file&#x60; is base64 encoded
    - data::String : File data in text format
    - data_uri::String : File data URI
"""
Base.@kwdef mutable struct CreateDataReq <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = ""
    base64_encoded::Union{Nothing, Bool} = false
    data::Union{Nothing, String} = ""
    data_uri::Union{Nothing, String} = ""

    function CreateDataReq(object_type, name, description, base64_encoded, data, data_uri, )
        OpenAPI.validate_property(CreateDataReq, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateDataReq, Symbol("name"), name)
        OpenAPI.validate_property(CreateDataReq, Symbol("description"), description)
        OpenAPI.validate_property(CreateDataReq, Symbol("base64_encoded"), base64_encoded)
        OpenAPI.validate_property(CreateDataReq, Symbol("data"), data)
        OpenAPI.validate_property(CreateDataReq, Symbol("data_uri"), data_uri)
        return new(object_type, name, description, base64_encoded, data, data_uri, )
    end
end # type CreateDataReq

const _property_types_CreateDataReq = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("base64_encoded")=>"Bool", Symbol("data")=>"String", Symbol("data_uri")=>"String", )
OpenAPI.property_type(::Type{ CreateDataReq }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateDataReq[name]))}

function check_required(o::CreateDataReq)
    o.object_type === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateDataReq }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateDataReq", :enum, val, ["data"])
    end


    if name === Symbol("name")
        OpenAPI.validate_param(name, "CreateDataReq", :maxLength, val, 255)
        OpenAPI.validate_param(name, "CreateDataReq", :minLength, val, 1)
    end

    if name === Symbol("description")
        OpenAPI.validate_param(name, "CreateDataReq", :maxLength, val, 2048)
    end



end