# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_Union_ExperimentRsp__ListModelsRspItem__CreateExperimentShareRsp__

    SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::Data1
"""
Base.@kwdef mutable struct SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, Data1 }

    function SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp(status, data, )
        OpenAPI.validate_property(SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp

const _property_types_SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"Data1", )
OpenAPI.property_type(::Type{ SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp[name]))}

function check_required(o::SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp", :enum, val, ["ok"])
    end


end
