# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetTokensRsp

    GetTokensRsp(;
        id=nothing,
        token=nothing,
        token_name=nothing,
        token_desc=nothing,
        token_expire=nothing,
    )

    - id::Int64
    - token::String
    - token_name::String
    - token_desc::String
    - token_expire::ZonedDateTime
"""
Base.@kwdef mutable struct GetTokensRsp <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    token::Union{Nothing, String} = nothing
    token_name::Union{Nothing, String} = nothing
    token_desc::Union{Nothing, String} = nothing
    token_expire::Union{Nothing, ZonedDateTime} = nothing

    function GetTokensRsp(id, token, token_name, token_desc, token_expire, )
        OpenAPI.validate_property(GetTokensRsp, Symbol("id"), id)
        OpenAPI.validate_property(GetTokensRsp, Symbol("token"), token)
        OpenAPI.validate_property(GetTokensRsp, Symbol("token_name"), token_name)
        OpenAPI.validate_property(GetTokensRsp, Symbol("token_desc"), token_desc)
        OpenAPI.validate_property(GetTokensRsp, Symbol("token_expire"), token_expire)
        return new(id, token, token_name, token_desc, token_expire, )
    end
end # type GetTokensRsp

const _property_types_GetTokensRsp = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("token")=>"String", Symbol("token_name")=>"String", Symbol("token_desc")=>"String", Symbol("token_expire")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ GetTokensRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetTokensRsp[name]))}

function check_required(o::GetTokensRsp)
    o.id === nothing && (return false)
    o.token === nothing && (return false)
    o.token_name === nothing && (return false)
    o.token_desc === nothing && (return false)
    o.token_expire === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetTokensRsp }, name::Symbol, val)





    if name === Symbol("token_expire")
        OpenAPI.validate_param(name, "GetTokensRsp", :format, val, "date-time")
    end
end