# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :CloudFunctionKind)
    const CloudFunctionKind = String
else
    @warn("Skipping redefinition of CloudFunctionKind to String")
end
