# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""UUUU28b510deefc97bb409a5d7911e299314_data

    UUUU28b510deefc97bb409a5d7911e299314Data(; value=nothing)
"""
mutable struct UUUU28b510deefc97bb409a5d7911e299314Data <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ExperimentRsp, ViewModelsRsp, WorkflowRunRsp }
    UUUU28b510deefc97bb409a5d7911e299314Data() = new()
    UUUU28b510deefc97bb409a5d7911e299314Data(value) = new(value)
end # type UUUU28b510deefc97bb409a5d7911e299314Data

function OpenAPI.property_type(::Type{ UUUU28b510deefc97bb409a5d7911e299314Data }, name::Symbol, json::Dict{String,Any})
    discriminator = json["object_type"]
    if discriminator == "experiment"
        return eval(Base.Meta.parse("ExperimentRsp"))
    elseif discriminator == "model"
        return eval(Base.Meta.parse("ViewModelsRsp"))
    elseif discriminator == "workflow.run"
        return eval(Base.Meta.parse("WorkflowRunRsp"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for UUUU28b510deefc97bb409a5d7911e299314Data"))
end