# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Auth0ConfigRsp

    Auth0ConfigRsp(;
        Domain=nothing,
        ClientID=nothing,
    )

    - Domain::String
    - ClientID::String
"""
Base.@kwdef mutable struct Auth0ConfigRsp <: OpenAPI.APIModel
    Domain::Union{Nothing, String} = nothing
    ClientID::Union{Nothing, String} = nothing

    function Auth0ConfigRsp(Domain, ClientID, )
        OpenAPI.validate_property(Auth0ConfigRsp, Symbol("Domain"), Domain)
        OpenAPI.validate_property(Auth0ConfigRsp, Symbol("ClientID"), ClientID)
        return new(Domain, ClientID, )
    end
end # type Auth0ConfigRsp

const _property_types_Auth0ConfigRsp = Dict{Symbol,String}(Symbol("Domain")=>"String", Symbol("ClientID")=>"String", )
OpenAPI.property_type(::Type{ Auth0ConfigRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Auth0ConfigRsp[name]))}

function check_required(o::Auth0ConfigRsp)
    o.Domain === nothing && (return false)
    o.ClientID === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Auth0ConfigRsp }, name::Symbol, val)


end