# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_ListingRspData_Union_ListExperimentRsp__ListModelsRspItem___

    SuccRspListingRspDataUnionListExperimentRspListModelsRspItem(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::ListingRspDataUnionListExperimentRspListModelsRspItem
"""
Base.@kwdef mutable struct SuccRspListingRspDataUnionListExperimentRspListModelsRspItem <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, ListingRspDataUnionListExperimentRspListModelsRspItem }

    function SuccRspListingRspDataUnionListExperimentRspListModelsRspItem(status, data, )
        OpenAPI.validate_property(SuccRspListingRspDataUnionListExperimentRspListModelsRspItem, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspListingRspDataUnionListExperimentRspListModelsRspItem, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspListingRspDataUnionListExperimentRspListModelsRspItem

const _property_types_SuccRspListingRspDataUnionListExperimentRspListModelsRspItem = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"ListingRspDataUnionListExperimentRspListModelsRspItem", )
OpenAPI.property_type(::Type{ SuccRspListingRspDataUnionListExperimentRspListModelsRspItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspListingRspDataUnionListExperimentRspListModelsRspItem[name]))}

function check_required(o::SuccRspListingRspDataUnionListExperimentRspListModelsRspItem)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspListingRspDataUnionListExperimentRspListModelsRspItem }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspListingRspDataUnionListExperimentRspListModelsRspItem", :enum, val, ["ok"])
    end


end
