# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_NoneType_

    SuccRspNoneType(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::Null
"""
Base.@kwdef mutable struct SuccRspNoneType <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, Null }

    function SuccRspNoneType(status, data, )
        OpenAPI.validate_property(SuccRspNoneType, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspNoneType, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspNoneType

const _property_types_SuccRspNoneType = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"Null", )
OpenAPI.property_type(::Type{ SuccRspNoneType }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspNoneType[name]))}

function check_required(o::SuccRspNoneType)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspNoneType }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspNoneType", :enum, val, ["ok"])
    end


end