# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_GetModelShareRsp_

    SuccRspGetModelShareRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::GetModelShareRsp
"""
Base.@kwdef mutable struct SuccRspGetModelShareRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, GetModelShareRsp }

    function SuccRspGetModelShareRsp(status, data, )
        OpenAPI.validate_property(SuccRspGetModelShareRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspGetModelShareRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspGetModelShareRsp

const _property_types_SuccRspGetModelShareRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"GetModelShareRsp", )
OpenAPI.property_type(::Type{ SuccRspGetModelShareRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspGetModelShareRsp[name]))}

function check_required(o::SuccRspGetModelShareRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspGetModelShareRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspGetModelShareRsp", :enum, val, ["ok"])
    end


end
