# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_UserLoginRsp_

    SuccRspUserLoginRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::UserLoginRsp
"""
Base.@kwdef mutable struct SuccRspUserLoginRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, UserLoginRsp }

    function SuccRspUserLoginRsp(status, data, )
        OpenAPI.validate_property(SuccRspUserLoginRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspUserLoginRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspUserLoginRsp

const _property_types_SuccRspUserLoginRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"UserLoginRsp", )
OpenAPI.property_type(::Type{ SuccRspUserLoginRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspUserLoginRsp[name]))}

function check_required(o::SuccRspUserLoginRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspUserLoginRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspUserLoginRsp", :enum, val, ["ok"])
    end


end