# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListingRsp_ListObjectRsp_

    ListingRspListObjectRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::ListingRspDataListObjectRsp
"""
Base.@kwdef mutable struct ListingRspListObjectRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, ListingRspDataListObjectRsp }

    function ListingRspListObjectRsp(status, data, )
        OpenAPI.validate_property(ListingRspListObjectRsp, Symbol("status"), status)
        OpenAPI.validate_property(ListingRspListObjectRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type ListingRspListObjectRsp

const _property_types_ListingRspListObjectRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"ListingRspDataListObjectRsp", )
OpenAPI.property_type(::Type{ ListingRspListObjectRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListingRspListObjectRsp[name]))}

function check_required(o::ListingRspListObjectRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListingRspListObjectRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "ListingRspListObjectRsp", :enum, val, ["ok"])
    end


end
