# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Payload_2

    Payload2(; value=nothing)
"""
mutable struct Payload2 <: OpenAPI.OneOfAPIModel
    value::Any # Union{ UpdateExperiment, UpdateModel }
    Payload2() = new()
    Payload2(value) = new(value)
end # type Payload2

function OpenAPI.property_type(::Type{ Payload2 }, name::Symbol, json::Dict{String,Any})
    discriminator = json["object_type"]
    if discriminator == "experiment"
        return eval(Base.Meta.parse("UpdateExperiment"))
    elseif discriminator == "model"
        return eval(Base.Meta.parse("UpdateModel"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for Payload2"))
end
