# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UUUUe66fb9eb8c8e63948bf34d0b2349c841

    UUUUe66fb9eb8c8e63948bf34d0b2349c841(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::UUUUe66fb9eb8c8e63948bf34d0b2349c841Data
"""
Base.@kwdef mutable struct UUUUe66fb9eb8c8e63948bf34d0b2349c841 <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, UUUUe66fb9eb8c8e63948bf34d0b2349c841Data }

    function UUUUe66fb9eb8c8e63948bf34d0b2349c841(status, data, )
        OpenAPI.validate_property(UUUUe66fb9eb8c8e63948bf34d0b2349c841, Symbol("status"), status)
        OpenAPI.validate_property(UUUUe66fb9eb8c8e63948bf34d0b2349c841, Symbol("data"), data)
        return new(status, data, )
    end
end # type UUUUe66fb9eb8c8e63948bf34d0b2349c841

const _property_types_UUUUe66fb9eb8c8e63948bf34d0b2349c841 = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"UUUUe66fb9eb8c8e63948bf34d0b2349c841Data", )
OpenAPI.property_type(::Type{ UUUUe66fb9eb8c8e63948bf34d0b2349c841 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UUUUe66fb9eb8c8e63948bf34d0b2349c841[name]))}

function check_required(o::UUUUe66fb9eb8c8e63948bf34d0b2349c841)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UUUUe66fb9eb8c8e63948bf34d0b2349c841 }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "UUUUe66fb9eb8c8e63948bf34d0b2349c841", :enum, val, ["ok"])
    end


end