# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UUUU28b510deefc97bb409a5d7911e299314

    UUUU28b510deefc97bb409a5d7911e299314(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::UUUU28b510deefc97bb409a5d7911e299314Data
"""
Base.@kwdef mutable struct UUUU28b510deefc97bb409a5d7911e299314 <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, UUUU28b510deefc97bb409a5d7911e299314Data }

    function UUUU28b510deefc97bb409a5d7911e299314(status, data, )
        OpenAPI.validate_property(UUUU28b510deefc97bb409a5d7911e299314, Symbol("status"), status)
        OpenAPI.validate_property(UUUU28b510deefc97bb409a5d7911e299314, Symbol("data"), data)
        return new(status, data, )
    end
end # type UUUU28b510deefc97bb409a5d7911e299314

const _property_types_UUUU28b510deefc97bb409a5d7911e299314 = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"UUUU28b510deefc97bb409a5d7911e299314Data", )
OpenAPI.property_type(::Type{ UUUU28b510deefc97bb409a5d7911e299314 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UUUU28b510deefc97bb409a5d7911e299314[name]))}

function check_required(o::UUUU28b510deefc97bb409a5d7911e299314)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UUUU28b510deefc97bb409a5d7911e299314 }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "UUUU28b510deefc97bb409a5d7911e299314", :enum, val, ["ok"])
    end


end