# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_DemoListRsp_

    SuccRspDemoListRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::DemoListRsp
"""
Base.@kwdef mutable struct SuccRspDemoListRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, DemoListRsp }

    function SuccRspDemoListRsp(status, data, )
        OpenAPI.validate_property(SuccRspDemoListRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspDemoListRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspDemoListRsp

const _property_types_SuccRspDemoListRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"DemoListRsp", )
OpenAPI.property_type(::Type{ SuccRspDemoListRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspDemoListRsp[name]))}

function check_required(o::SuccRspDemoListRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspDemoListRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspDemoListRsp", :enum, val, ["ok"])
    end


end