# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExperimentPlotRsp

    ExperimentPlotRsp(;
        object_type=nothing,
        url=nothing,
    )

    - object_type::String
    - url::String
"""
Base.@kwdef mutable struct ExperimentPlotRsp <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function ExperimentPlotRsp(object_type, url, )
        OpenAPI.validate_property(ExperimentPlotRsp, Symbol("object_type"), object_type)
        OpenAPI.validate_property(ExperimentPlotRsp, Symbol("url"), url)
        return new(object_type, url, )
    end
end # type ExperimentPlotRsp

const _property_types_ExperimentPlotRsp = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ ExperimentPlotRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExperimentPlotRsp[name]))}

function check_required(o::ExperimentPlotRsp)
    o.object_type === nothing && (return false)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ExperimentPlotRsp }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "ExperimentPlotRsp", :enum, val, ["experiment.plot"])
    end


end