# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeleteModelShare

    DeleteModelShare(;
        share_id=nothing,
    )

    - share_id::String : \&quot;-\&quot;separated share ids
"""
Base.@kwdef mutable struct DeleteModelShare <: OpenAPI.APIModel
    share_id::Union{Nothing, String} = nothing

    function DeleteModelShare(share_id, )
        OpenAPI.validate_property(DeleteModelShare, Symbol("share_id"), share_id)
        return new(share_id, )
    end
end # type DeleteModelShare

const _property_types_DeleteModelShare = Dict{Symbol,String}(Symbol("share_id")=>"String", )
OpenAPI.property_type(::Type{ DeleteModelShare }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeleteModelShare[name]))}

function check_required(o::DeleteModelShare)
    o.share_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DeleteModelShare }, name::Symbol, val)

end
