# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_GetSampleDataRsp_

    SuccRspGetSampleDataRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::GetSampleDataRsp
"""
Base.@kwdef mutable struct SuccRspGetSampleDataRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, GetSampleDataRsp }

    function SuccRspGetSampleDataRsp(status, data, )
        OpenAPI.validate_property(SuccRspGetSampleDataRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspGetSampleDataRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspGetSampleDataRsp

const _property_types_SuccRspGetSampleDataRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"GetSampleDataRsp", )
OpenAPI.property_type(::Type{ SuccRspGetSampleDataRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspGetSampleDataRsp[name]))}

function check_required(o::SuccRspGetSampleDataRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspGetSampleDataRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspGetSampleDataRsp", :enum, val, ["ok"])
    end


end
