# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""UUUUc9932bea1f007b34d507c4c4c680b4a7_objects_inner

    UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(; value=nothing)
"""
mutable struct UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner <: OpenAPI.OneOfAPIModel
    value::Any # Union{ CreateCallbackRsp, CreateDataRsp, CreateEventRsp, CreateRelationRsp, CreateWorkflowRsp, ListExperimentRsp, ListModelsRspItem }
    UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner() = new()
    UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(value) = new(value)
end # type UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner

function OpenAPI.property_type(::Type{ UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner }, name::Symbol, json::Dict{String,Any})
    discriminator = json["object_type"]
    if discriminator == "callback"
        return eval(Base.Meta.parse("CreateCallbackRsp"))
    elseif discriminator == "data"
        return eval(Base.Meta.parse("CreateDataRsp"))
    elseif discriminator == "event"
        return eval(Base.Meta.parse("CreateEventRsp"))
    elseif discriminator == "experiment"
        return eval(Base.Meta.parse("ListExperimentRsp"))
    elseif discriminator == "model"
        return eval(Base.Meta.parse("ListModelsRspItem"))
    elseif discriminator == "relation"
        return eval(Base.Meta.parse("CreateRelationRsp"))
    elseif discriminator == "workflow"
        return eval(Base.Meta.parse("CreateWorkflowRsp"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner"))
end