# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SaveAnalyzerResultReq

    SaveAnalyzerResultReq(;
        object_type=nothing,
        return_code=nothing,
        errlines=nothing,
        result=nothing,
    )

    - object_type::String
    - return_code::Int64
    - errlines::Vector{String}
    - result::String
"""
Base.@kwdef mutable struct SaveAnalyzerResultReq <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    return_code::Union{Nothing, Int64} = nothing
    errlines::Union{Nothing, Vector{String}} = nothing
    result::Union{Nothing, String} = nothing

    function SaveAnalyzerResultReq(object_type, return_code, errlines, result, )
        OpenAPI.validate_property(SaveAnalyzerResultReq, Symbol("object_type"), object_type)
        OpenAPI.validate_property(SaveAnalyzerResultReq, Symbol("return_code"), return_code)
        OpenAPI.validate_property(SaveAnalyzerResultReq, Symbol("errlines"), errlines)
        OpenAPI.validate_property(SaveAnalyzerResultReq, Symbol("result"), result)
        return new(object_type, return_code, errlines, result, )
    end
end # type SaveAnalyzerResultReq

const _property_types_SaveAnalyzerResultReq = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("return_code")=>"Int64", Symbol("errlines")=>"Vector{String}", Symbol("result")=>"String", )
OpenAPI.property_type(::Type{ SaveAnalyzerResultReq }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SaveAnalyzerResultReq[name]))}

function check_required(o::SaveAnalyzerResultReq)
    o.object_type === nothing && (return false)
    o.return_code === nothing && (return false)
    o.errlines === nothing && (return false)
    o.result === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SaveAnalyzerResultReq }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "SaveAnalyzerResultReq", :enum, val, ["workflow.analyzer_result"])
    end




end