# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateCallbackRsp

    CreateCallbackRsp(;
        object_type=nothing,
        short_id=nothing,
        lang=nothing,
        code=nothing,
        token=nothing,
        created_at=nothing,
    )

    - object_type::String
    - short_id::String
    - lang::String
    - code::String
    - token::String
    - created_at::ZonedDateTime
"""
Base.@kwdef mutable struct CreateCallbackRsp <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    short_id::Union{Nothing, String} = nothing
    lang::Union{Nothing, String} = nothing
    code::Union{Nothing, String} = nothing
    token::Union{Nothing, String} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing

    function CreateCallbackRsp(object_type, short_id, lang, code, token, created_at, )
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("short_id"), short_id)
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("lang"), lang)
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("code"), code)
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("token"), token)
        OpenAPI.validate_property(CreateCallbackRsp, Symbol("created_at"), created_at)
        return new(object_type, short_id, lang, code, token, created_at, )
    end
end # type CreateCallbackRsp

const _property_types_CreateCallbackRsp = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("short_id")=>"String", Symbol("lang")=>"String", Symbol("code")=>"String", Symbol("token")=>"String", Symbol("created_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ CreateCallbackRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateCallbackRsp[name]))}

function check_required(o::CreateCallbackRsp)
    o.object_type === nothing && (return false)
    o.short_id === nothing && (return false)
    o.lang === nothing && (return false)
    o.code === nothing && (return false)
    o.token === nothing && (return false)
    o.created_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateCallbackRsp }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateCallbackRsp", :enum, val, ["callback"])
    end






    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "CreateCallbackRsp", :format, val, "date-time")
    end
end