# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListingRspData_NotificationDict_

    ListingRspDataNotificationDict(;
        total=nothing,
        page=nothing,
        count_per_page=nothing,
        objects=nothing,
    )

    - total::Int64
    - page::Int64
    - count_per_page::Int64
    - objects::Vector{NotificationDict}
"""
Base.@kwdef mutable struct ListingRspDataNotificationDict <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    page::Union{Nothing, Int64} = nothing
    count_per_page::Union{Nothing, Int64} = nothing
    objects::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{NotificationDict} }

    function ListingRspDataNotificationDict(total, page, count_per_page, objects, )
        OpenAPI.validate_property(ListingRspDataNotificationDict, Symbol("total"), total)
        OpenAPI.validate_property(ListingRspDataNotificationDict, Symbol("page"), page)
        OpenAPI.validate_property(ListingRspDataNotificationDict, Symbol("count_per_page"), count_per_page)
        OpenAPI.validate_property(ListingRspDataNotificationDict, Symbol("objects"), objects)
        return new(total, page, count_per_page, objects, )
    end
end # type ListingRspDataNotificationDict

const _property_types_ListingRspDataNotificationDict = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("page")=>"Int64", Symbol("count_per_page")=>"Int64", Symbol("objects")=>"Vector{NotificationDict}", )
OpenAPI.property_type(::Type{ ListingRspDataNotificationDict }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListingRspDataNotificationDict[name]))}

function check_required(o::ListingRspDataNotificationDict)
    o.total === nothing && (return false)
    o.page === nothing && (return false)
    o.count_per_page === nothing && (return false)
    o.objects === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListingRspDataNotificationDict }, name::Symbol, val)




end