# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_File

    File(;
        name=nothing,
        type="file",
    )

    - name::String
    - type::String
"""
Base.@kwdef mutable struct File <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = "file"

    function File(name, type, )
        OpenAPI.validate_property(File, Symbol("name"), name)
        OpenAPI.validate_property(File, Symbol("type"), type)
        return new(name, type, )
    end
end # type File

const _property_types_File = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ File }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_File[name]))}

function check_required(o::File)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ File }, name::Symbol, val)


end
