# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UUUU256545f429a0ce36bfec4159b7df9cf4

    UUUU256545f429a0ce36bfec4159b7df9cf4(;
        total=nothing,
        page=nothing,
        count_per_page=nothing,
        objects=nothing,
    )

    - total::Int64
    - page::Int64
    - count_per_page::Int64
    - objects::Vector{UUUU256545f429a0ce36bfec4159b7df9cf4ObjectsInner}
"""
Base.@kwdef mutable struct UUUU256545f429a0ce36bfec4159b7df9cf4 <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    page::Union{Nothing, Int64} = nothing
    count_per_page::Union{Nothing, Int64} = nothing
    objects::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{UUUU256545f429a0ce36bfec4159b7df9cf4ObjectsInner} }

    function UUUU256545f429a0ce36bfec4159b7df9cf4(total, page, count_per_page, objects, )
        OpenAPI.validate_property(UUUU256545f429a0ce36bfec4159b7df9cf4, Symbol("total"), total)
        OpenAPI.validate_property(UUUU256545f429a0ce36bfec4159b7df9cf4, Symbol("page"), page)
        OpenAPI.validate_property(UUUU256545f429a0ce36bfec4159b7df9cf4, Symbol("count_per_page"), count_per_page)
        OpenAPI.validate_property(UUUU256545f429a0ce36bfec4159b7df9cf4, Symbol("objects"), objects)
        return new(total, page, count_per_page, objects, )
    end
end # type UUUU256545f429a0ce36bfec4159b7df9cf4

const _property_types_UUUU256545f429a0ce36bfec4159b7df9cf4 = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("page")=>"Int64", Symbol("count_per_page")=>"Int64", Symbol("objects")=>"Vector{UUUU256545f429a0ce36bfec4159b7df9cf4ObjectsInner}", )
OpenAPI.property_type(::Type{ UUUU256545f429a0ce36bfec4159b7df9cf4 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UUUU256545f429a0ce36bfec4159b7df9cf4[name]))}

function check_required(o::UUUU256545f429a0ce36bfec4159b7df9cf4)
    o.total === nothing && (return false)
    o.page === nothing && (return false)
    o.count_per_page === nothing && (return false)
    o.objects === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UUUU256545f429a0ce36bfec4159b7df9cf4 }, name::Symbol, val)




end