# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UUUU3d00ddc80a048e8fc9eddc3c1943d9f1

    UUUU3d00ddc80a048e8fc9eddc3c1943d9f1(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::UUUU256545f429a0ce36bfec4159b7df9cf4
"""
Base.@kwdef mutable struct UUUU3d00ddc80a048e8fc9eddc3c1943d9f1 <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, UUUU256545f429a0ce36bfec4159b7df9cf4 }

    function UUUU3d00ddc80a048e8fc9eddc3c1943d9f1(status, data, )
        OpenAPI.validate_property(UUUU3d00ddc80a048e8fc9eddc3c1943d9f1, Symbol("status"), status)
        OpenAPI.validate_property(UUUU3d00ddc80a048e8fc9eddc3c1943d9f1, Symbol("data"), data)
        return new(status, data, )
    end
end # type UUUU3d00ddc80a048e8fc9eddc3c1943d9f1

const _property_types_UUUU3d00ddc80a048e8fc9eddc3c1943d9f1 = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"UUUU256545f429a0ce36bfec4159b7df9cf4", )
OpenAPI.property_type(::Type{ UUUU3d00ddc80a048e8fc9eddc3c1943d9f1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UUUU3d00ddc80a048e8fc9eddc3c1943d9f1[name]))}

function check_required(o::UUUU3d00ddc80a048e8fc9eddc3c1943d9f1)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UUUU3d00ddc80a048e8fc9eddc3c1943d9f1 }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "UUUU3d00ddc80a048e8fc9eddc3c1943d9f1", :enum, val, ["ok"])
    end


end