# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Data

    Data(; value=nothing)
"""
mutable struct Data <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ ExperimentRsp, ViewModelsRsp }
    Data() = new()
    Data(value) = new(value)
end # type Data

function OpenAPI.property_type(::Type{ Data }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(Data, name)
end