# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateEventReq

    CreateEventReq(;
        object_type=nothing,
        name=nothing,
    )

    - object_type::String
    - name::String
"""
Base.@kwdef mutable struct CreateEventReq <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function CreateEventReq(object_type, name, )
        OpenAPI.validate_property(CreateEventReq, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateEventReq, Symbol("name"), name)
        return new(object_type, name, )
    end
end # type CreateEventReq

const _property_types_CreateEventReq = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ CreateEventReq }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateEventReq[name]))}

function check_required(o::CreateEventReq)
    o.object_type === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateEventReq }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateEventReq", :enum, val, ["event"])
    end


end
