# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListingRspData_Union_ListExperimentRsp__ListModelsRspItem__CreateEventRsp__CreateCallbackRsp__CreateRelationRsp__

    ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp(;
        total=nothing,
        page=nothing,
        count_per_page=nothing,
        objects=nothing,
    )

    - total::Int64
    - page::Int64
    - count_per_page::Int64
    - objects::Vector{ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRspObjectsInner}
"""
Base.@kwdef mutable struct ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    page::Union{Nothing, Int64} = nothing
    count_per_page::Union{Nothing, Int64} = nothing
    objects::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRspObjectsInner} }

    function ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp(total, page, count_per_page, objects, )
        OpenAPI.validate_property(ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp, Symbol("total"), total)
        OpenAPI.validate_property(ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp, Symbol("page"), page)
        OpenAPI.validate_property(ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp, Symbol("count_per_page"), count_per_page)
        OpenAPI.validate_property(ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp, Symbol("objects"), objects)
        return new(total, page, count_per_page, objects, )
    end
end # type ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp

const _property_types_ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("page")=>"Int64", Symbol("count_per_page")=>"Int64", Symbol("objects")=>"Vector{ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRspObjectsInner}", )
OpenAPI.property_type(::Type{ ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp[name]))}

function check_required(o::ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp)
    o.total === nothing && (return false)
    o.page === nothing && (return false)
    o.count_per_page === nothing && (return false)
    o.objects === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListingRspDataUnionListExperimentRspListModelsRspItemCreateEventRspCreateCallbackRspCreateRelationRsp }, name::Symbol, val)




end
