# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateWorkflowRsp

    CreateWorkflowRsp(;
        object_type=nothing,
        short_id=nothing,
        name=nothing,
        model_id=nothing,
        model_name=nothing,
        data_id=nothing,
        data_name=nothing,
        experiment_id=nothing,
        experiment_name=nothing,
        analyzer_id=nothing,
        analyzer_name=nothing,
        created_at=nothing,
        updated_at=nothing,
        startup_script=nothing,
    )

    - object_type::String
    - short_id::String
    - name::String
    - model_id::String
    - model_name::String
    - data_id::String
    - data_name::String
    - experiment_id::String
    - experiment_name::String
    - analyzer_id::String
    - analyzer_name::String
    - created_at::ZonedDateTime
    - updated_at::ZonedDateTime
    - startup_script::String
"""
Base.@kwdef mutable struct CreateWorkflowRsp <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    short_id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    model_id::Union{Nothing, String} = nothing
    model_name::Union{Nothing, String} = nothing
    data_id::Union{Nothing, String} = nothing
    data_name::Union{Nothing, String} = nothing
    experiment_id::Union{Nothing, String} = nothing
    experiment_name::Union{Nothing, String} = nothing
    analyzer_id::Union{Nothing, String} = nothing
    analyzer_name::Union{Nothing, String} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    startup_script::Union{Nothing, String} = nothing

    function CreateWorkflowRsp(object_type, short_id, name, model_id, model_name, data_id, data_name, experiment_id, experiment_name, analyzer_id, analyzer_name, created_at, updated_at, startup_script, )
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("short_id"), short_id)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("name"), name)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("model_id"), model_id)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("model_name"), model_name)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("data_id"), data_id)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("data_name"), data_name)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("experiment_id"), experiment_id)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("experiment_name"), experiment_name)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("analyzer_id"), analyzer_id)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("analyzer_name"), analyzer_name)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("created_at"), created_at)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(CreateWorkflowRsp, Symbol("startup_script"), startup_script)
        return new(object_type, short_id, name, model_id, model_name, data_id, data_name, experiment_id, experiment_name, analyzer_id, analyzer_name, created_at, updated_at, startup_script, )
    end
end # type CreateWorkflowRsp

const _property_types_CreateWorkflowRsp = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("short_id")=>"String", Symbol("name")=>"String", Symbol("model_id")=>"String", Symbol("model_name")=>"String", Symbol("data_id")=>"String", Symbol("data_name")=>"String", Symbol("experiment_id")=>"String", Symbol("experiment_name")=>"String", Symbol("analyzer_id")=>"String", Symbol("analyzer_name")=>"String", Symbol("created_at")=>"ZonedDateTime", Symbol("updated_at")=>"ZonedDateTime", Symbol("startup_script")=>"String", )
OpenAPI.property_type(::Type{ CreateWorkflowRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateWorkflowRsp[name]))}

function check_required(o::CreateWorkflowRsp)
    o.object_type === nothing && (return false)
    o.short_id === nothing && (return false)
    o.name === nothing && (return false)
    o.model_id === nothing && (return false)
    o.model_name === nothing && (return false)
    o.created_at === nothing && (return false)
    o.updated_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateWorkflowRsp }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateWorkflowRsp", :enum, val, ["workflow"])
    end












    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "CreateWorkflowRsp", :format, val, "date-time")
    end

    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "CreateWorkflowRsp", :format, val, "date-time")
    end

end