# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListingRspData_ListObjectRsp_

    ListingRspDataListObjectRsp(;
        total=nothing,
        page=nothing,
        count_per_page=nothing,
        objects=nothing,
    )

    - total::Int64
    - page::Int64
    - count_per_page::Int64
    - objects::Vector{ListObjectRsp}
"""
Base.@kwdef mutable struct ListingRspDataListObjectRsp <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    page::Union{Nothing, Int64} = nothing
    count_per_page::Union{Nothing, Int64} = nothing
    objects::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ListObjectRsp} }

    function ListingRspDataListObjectRsp(total, page, count_per_page, objects, )
        OpenAPI.validate_property(ListingRspDataListObjectRsp, Symbol("total"), total)
        OpenAPI.validate_property(ListingRspDataListObjectRsp, Symbol("page"), page)
        OpenAPI.validate_property(ListingRspDataListObjectRsp, Symbol("count_per_page"), count_per_page)
        OpenAPI.validate_property(ListingRspDataListObjectRsp, Symbol("objects"), objects)
        return new(total, page, count_per_page, objects, )
    end
end # type ListingRspDataListObjectRsp

const _property_types_ListingRspDataListObjectRsp = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("page")=>"Int64", Symbol("count_per_page")=>"Int64", Symbol("objects")=>"Vector{ListObjectRsp}", )
OpenAPI.property_type(::Type{ ListingRspDataListObjectRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListingRspDataListObjectRsp[name]))}

function check_required(o::ListingRspDataListObjectRsp)
    o.total === nothing && (return false)
    o.page === nothing && (return false)
    o.count_per_page === nothing && (return false)
    o.objects === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListingRspDataListObjectRsp }, name::Symbol, val)




end
