# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_GetTokensRsp_

    SuccRspGetTokensRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::GetTokensRsp
"""
Base.@kwdef mutable struct SuccRspGetTokensRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, GetTokensRsp }

    function SuccRspGetTokensRsp(status, data, )
        OpenAPI.validate_property(SuccRspGetTokensRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspGetTokensRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspGetTokensRsp

const _property_types_SuccRspGetTokensRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"GetTokensRsp", )
OpenAPI.property_type(::Type{ SuccRspGetTokensRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspGetTokensRsp[name]))}

function check_required(o::SuccRspGetTokensRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspGetTokensRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspGetTokensRsp", :enum, val, ["ok"])
    end


end
