# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""ListingRspData_Union_ListExperimentRsp__ListModelsRspItem___objects_inner

    ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner(; value=nothing)
"""
mutable struct ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ ListExperimentRsp, ListModelsRspItem }
    ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner() = new()
    ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner(value) = new(value)
end # type ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner

function OpenAPI.property_type(::Type{ ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner, name)
end
