# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_Union_ExperimentRsp__ViewModelsRsp__

    SuccRspUnionExperimentRspViewModelsRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::Data3
"""
Base.@kwdef mutable struct SuccRspUnionExperimentRspViewModelsRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, Data3 }

    function SuccRspUnionExperimentRspViewModelsRsp(status, data, )
        OpenAPI.validate_property(SuccRspUnionExperimentRspViewModelsRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspUnionExperimentRspViewModelsRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspUnionExperimentRspViewModelsRsp

const _property_types_SuccRspUnionExperimentRspViewModelsRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"Data3", )
OpenAPI.property_type(::Type{ SuccRspUnionExperimentRspViewModelsRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspUnionExperimentRspViewModelsRsp[name]))}

function check_required(o::SuccRspUnionExperimentRspViewModelsRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspUnionExperimentRspViewModelsRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspUnionExperimentRspViewModelsRsp", :enum, val, ["ok"])
    end


end
