# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ViewModelShareInfo

    ViewModelShareInfo(;
        id=nothing,
        public=nothing,
    )

    - id::Int64
    - public::Bool
"""
Base.@kwdef mutable struct ViewModelShareInfo <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    public::Union{Nothing, Bool} = nothing

    function ViewModelShareInfo(id, public, )
        OpenAPI.validate_property(ViewModelShareInfo, Symbol("id"), id)
        OpenAPI.validate_property(ViewModelShareInfo, Symbol("public"), public)
        return new(id, public, )
    end
end # type ViewModelShareInfo

const _property_types_ViewModelShareInfo = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("public")=>"Bool", )
OpenAPI.property_type(::Type{ ViewModelShareInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ViewModelShareInfo[name]))}

function check_required(o::ViewModelShareInfo)
    o.id === nothing && (return false)
    o.public === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ViewModelShareInfo }, name::Symbol, val)


end
