# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateArtifactRsp

    CreateArtifactRsp(;
        object_type=nothing,
        name=nothing,
        description=nothing,
        short_id=nothing,
        created_at=nothing,
        updated_at=nothing,
    )

    - object_type::String
    - name::String
    - description::String
    - short_id::String
    - created_at::ZonedDateTime
    - updated_at::ZonedDateTime
"""
Base.@kwdef mutable struct CreateArtifactRsp <: OpenAPI.APIModel
    object_type::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    short_id::Union{Nothing, String} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing

    function CreateArtifactRsp(object_type, name, description, short_id, created_at, updated_at, )
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("object_type"), object_type)
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("name"), name)
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("description"), description)
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("short_id"), short_id)
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("created_at"), created_at)
        OpenAPI.validate_property(CreateArtifactRsp, Symbol("updated_at"), updated_at)
        return new(object_type, name, description, short_id, created_at, updated_at, )
    end
end # type CreateArtifactRsp

const _property_types_CreateArtifactRsp = Dict{Symbol,String}(Symbol("object_type")=>"String", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("short_id")=>"String", Symbol("created_at")=>"ZonedDateTime", Symbol("updated_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ CreateArtifactRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateArtifactRsp[name]))}

function check_required(o::CreateArtifactRsp)
    o.object_type === nothing && (return false)
    o.name === nothing && (return false)
    o.description === nothing && (return false)
    o.short_id === nothing && (return false)
    o.created_at === nothing && (return false)
    o.updated_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateArtifactRsp }, name::Symbol, val)

    if name === Symbol("object_type")
        OpenAPI.validate_param(name, "CreateArtifactRsp", :enum, val, ["artifact"])
    end





    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "CreateArtifactRsp", :format, val, "date-time")
    end

    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "CreateArtifactRsp", :format, val, "date-time")
    end
end