# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_DemoListItem

    DemoListItem(;
        name=nothing,
        url=nothing,
    )

    - name::String
    - url::String
"""
Base.@kwdef mutable struct DemoListItem <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function DemoListItem(name, url, )
        OpenAPI.validate_property(DemoListItem, Symbol("name"), name)
        OpenAPI.validate_property(DemoListItem, Symbol("url"), url)
        return new(name, url, )
    end
end # type DemoListItem

const _property_types_DemoListItem = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ DemoListItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DemoListItem[name]))}

function check_required(o::DemoListItem)
    o.name === nothing && (return false)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DemoListItem }, name::Symbol, val)


end
