# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_CreateExperimentShareRsp_

    SuccRspCreateExperimentShareRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::CreateExperimentShareRsp
"""
Base.@kwdef mutable struct SuccRspCreateExperimentShareRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, CreateExperimentShareRsp }

    function SuccRspCreateExperimentShareRsp(status, data, )
        OpenAPI.validate_property(SuccRspCreateExperimentShareRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspCreateExperimentShareRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspCreateExperimentShareRsp

const _property_types_SuccRspCreateExperimentShareRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"CreateExperimentShareRsp", )
OpenAPI.property_type(::Type{ SuccRspCreateExperimentShareRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspCreateExperimentShareRsp[name]))}

function check_required(o::SuccRspCreateExperimentShareRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspCreateExperimentShareRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspCreateExperimentShareRsp", :enum, val, ["ok"])
    end


end
