# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuccRsp_ListLinkedAccountRsp_

    SuccRspListLinkedAccountRsp(;
        status=nothing,
        data=nothing,
    )

    - status::String
    - data::ListLinkedAccountRsp
"""
Base.@kwdef mutable struct SuccRspListLinkedAccountRsp <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, ListLinkedAccountRsp }

    function SuccRspListLinkedAccountRsp(status, data, )
        OpenAPI.validate_property(SuccRspListLinkedAccountRsp, Symbol("status"), status)
        OpenAPI.validate_property(SuccRspListLinkedAccountRsp, Symbol("data"), data)
        return new(status, data, )
    end
end # type SuccRspListLinkedAccountRsp

const _property_types_SuccRspListLinkedAccountRsp = Dict{Symbol,String}(Symbol("status")=>"String", Symbol("data")=>"ListLinkedAccountRsp", )
OpenAPI.property_type(::Type{ SuccRspListLinkedAccountRsp }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuccRspListLinkedAccountRsp[name]))}

function check_required(o::SuccRspListLinkedAccountRsp)
    o.status === nothing && (return false)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SuccRspListLinkedAccountRsp }, name::Symbol, val)

    if name === Symbol("status")
        OpenAPI.validate_param(name, "SuccRspListLinkedAccountRsp", :enum, val, ["ok"])
    end


end