# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct CommandApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `CommandApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ CommandApi }) = "https://api.coinfer.ai"

const _returntypes_run_command_CommandApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccRspAny,
)

function _oacinternal_run_command(_api::CommandApi, run_command_req::RunCommandReq; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_run_command_CommandApi, "/command", [], run_command_req)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Run command

Params:
- run_command_req::RunCommandReq (required)

Return: SuccRspAny, OpenAPI.Clients.ApiResponse
"""
function run_command(_api::CommandApi, run_command_req::RunCommandReq; _mediaType=nothing)
    _ctx = _oacinternal_run_command(_api, run_command_req; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function run_command(_api::CommandApi, response_stream::Channel, run_command_req::RunCommandReq; _mediaType=nothing)
    _ctx = _oacinternal_run_command(_api, run_command_req; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export run_command
