# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct SystemApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `SystemApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ SystemApi }) = "https://api.coinfer.ai"

const _returntypes_arviz_plot_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccRspPlotRsp,
    Regex("^" * replace("400", "x"=>".") * "\$") => ErrRsp,
)

function _oacinternal_arviz_plot(_api::SystemApi, plot_req::PlotReq; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_arviz_plot_SystemApi, "/sys/plot", [], plot_req)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Get Arviz plot data.

Params:
- plot_req::PlotReq (required)

Return: SuccRspPlotRsp, OpenAPI.Clients.ApiResponse
"""
function arviz_plot(_api::SystemApi, plot_req::PlotReq; _mediaType=nothing)
    _ctx = _oacinternal_arviz_plot(_api, plot_req; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function arviz_plot(_api::SystemApi, response_stream::Channel, plot_req::PlotReq; _mediaType=nothing)
    _ctx = _oacinternal_arviz_plot(_api, plot_req; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_config_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccRspGetConfigRsp,
    Regex("^" * replace("400", "x"=>".") * "\$") => ErrRsp,
)

function _oacinternal_config(_api::SystemApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_config_SystemApi, "/sys/config", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get configuration about how to run a model.

This API is used to get the configuration about how to run a model. Currently the configuration includes the URL of the proxy lambda function which is used to run the model.

Params:

Return: SuccRspGetConfigRsp, OpenAPI.Clients.ApiResponse
"""
function config(_api::SystemApi; _mediaType=nothing)
    _ctx = _oacinternal_config(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function config(_api::SystemApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_config(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_download_workflow_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccRspAny,
)

function _oacinternal_download_workflow(_api::SystemApi, objid::String; is_cloud=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_download_workflow_SystemApi, "/sys/download-workflow", ["GlobalAuth", ])
    OpenAPI.Clients.set_param(_ctx.query, "objid", objid; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "is_cloud", is_cloud; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Download workflow.

Params:
- objid::String (required)
- is_cloud::Bool

Return: SuccRspAny, OpenAPI.Clients.ApiResponse
"""
function download_workflow(_api::SystemApi, objid::String; is_cloud=nothing, _mediaType=nothing)
    _ctx = _oacinternal_download_workflow(_api, objid; is_cloud=is_cloud, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function download_workflow(_api::SystemApi, response_stream::Channel, objid::String; is_cloud=nothing, _mediaType=nothing)
    _ctx = _oacinternal_download_workflow(_api, objid; is_cloud=is_cloud, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_repository_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccRspDemoListRsp,
    Regex("^" * replace("400", "x"=>".") * "\$") => ErrRsp,
)

function _oacinternal_repository(_api::SystemApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_repository_SystemApi, "/sys/gallery", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List gallery data.

Params:

Return: SuccRspDemoListRsp, OpenAPI.Clients.ApiResponse
"""
function repository(_api::SystemApi; _mediaType=nothing)
    _ctx = _oacinternal_repository(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function repository(_api::SystemApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_repository(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export arviz_plot
export config
export download_workflow
export repository
