# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CloudFunctionTag(str, Enum):
    """
    All possible tags for cloudfunctions  Including: CloudFunctionManagedTag and CloudFunctionKind
    """

    """
    allowed enum values
    """
    INTERNAL = 'internal'
    BUILTIN = 'builtin'
    RESERVED = 'reserved'
    MODEL = 'model'
    CODE = 'code'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CloudFunctionTag from a JSON string"""
        return cls(json.loads(json_str))


