# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747269724+a7f6527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateModelShareRsp(BaseModel):
    """
    CreateModelShareRsp
    """ # noqa: E501
    id: StrictInt
    model_id: StrictStr
    model_name: StrictStr
    password: StrictStr
    created_at: datetime
    from_user: Optional[StrictStr] = None
    to_user: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "model_id", "model_name", "password", "created_at", "from_user", "to_user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateModelShareRsp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if from_user (nullable) is None
        # and model_fields_set contains the field
        if self.from_user is None and "from_user" in self.model_fields_set:
            _dict['from_user'] = None

        # set to None if to_user (nullable) is None
        # and model_fields_set contains the field
        if self.to_user is None and "to_user" in self.model_fields_set:
            _dict['to_user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateModelShareRsp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "model_id": obj.get("model_id"),
            "model_name": obj.get("model_name"),
            "password": obj.get("password"),
            "created_at": obj.get("created_at"),
            "from_user": obj.get("from_user"),
            "to_user": obj.get("to_user")
        })
        return _obj


