# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.experiment_rsp import ExperimentRsp
from openapi_client.models.model_run_script_rsp import ModelRunScriptRsp
from openapi_client.models.view_models_rsp import ViewModelsRsp
from openapi_client.models.workflow_run_rsp import WorkflowRunRsp
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

UUUUE66FB9EB8C8E63948BF34D0B2349C841DATA_ONE_OF_SCHEMAS = ["ExperimentRsp", "ModelRunScriptRsp", "ViewModelsRsp", "WorkflowRunRsp"]

class UUUUe66fb9eb8c8e63948bf34d0b2349c841Data(BaseModel):
    """
    UUUUe66fb9eb8c8e63948bf34d0b2349c841Data
    """
    # data type: ExperimentRsp
    oneof_schema_1_validator: Optional[ExperimentRsp] = None
    # data type: ViewModelsRsp
    oneof_schema_2_validator: Optional[ViewModelsRsp] = None
    # data type: WorkflowRunRsp
    oneof_schema_3_validator: Optional[WorkflowRunRsp] = None
    # data type: ModelRunScriptRsp
    oneof_schema_4_validator: Optional[ModelRunScriptRsp] = None
    actual_instance: Optional[Union[ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp]] = None
    one_of_schemas: Set[str] = { "ExperimentRsp", "ModelRunScriptRsp", "ViewModelsRsp", "WorkflowRunRsp" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = UUUUe66fb9eb8c8e63948bf34d0b2349c841Data.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExperimentRsp
        if not isinstance(v, ExperimentRsp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExperimentRsp`")
        else:
            match += 1
        # validate data type: ViewModelsRsp
        if not isinstance(v, ViewModelsRsp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ViewModelsRsp`")
        else:
            match += 1
        # validate data type: WorkflowRunRsp
        if not isinstance(v, WorkflowRunRsp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkflowRunRsp`")
        else:
            match += 1
        # validate data type: ModelRunScriptRsp
        if not isinstance(v, ModelRunScriptRsp):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelRunScriptRsp`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UUUUe66fb9eb8c8e63948bf34d0b2349c841Data with oneOf schemas: ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UUUUe66fb9eb8c8e63948bf34d0b2349c841Data with oneOf schemas: ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into ExperimentRsp
        try:
            instance.actual_instance = ExperimentRsp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ViewModelsRsp
        try:
            instance.actual_instance = ViewModelsRsp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkflowRunRsp
        try:
            instance.actual_instance = WorkflowRunRsp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ModelRunScriptRsp
        try:
            instance.actual_instance = ModelRunScriptRsp.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UUUUe66fb9eb8c8e63948bf34d0b2349c841Data with oneOf schemas: ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UUUUe66fb9eb8c8e63948bf34d0b2349c841Data with oneOf schemas: ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExperimentRsp, ModelRunScriptRsp, ViewModelsRsp, WorkflowRunRsp]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


