# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1750641818+35eeab7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_object_tmp import ListObjectTmp

class TestListObjectTmp(unittest.TestCase):
    """ListObjectTmp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListObjectTmp:
        """Test ListObjectTmp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListObjectTmp`
        """
        model = ListObjectTmp()
        if include_optional:
            return ListObjectTmp(
                page_no = 56,
                page_size = 56,
                object_type = 'model',
                with_share_info = True,
                shared_by_me = True,
                shared_with_me = True,
                model_ids = [
                    ''
                    ],
                status = 'NEW',
                run_on = 'Lambda',
                has_model = 'true',
                kind = 'model'
            )
        else:
            return ListObjectTmp(
                object_type = 'model',
        )
        """

    def testListObjectTmp(self):
        """Test ListObjectTmp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
