# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.soft_deleted_rsp import SoftDeletedRsp

class TestSoftDeletedRsp(unittest.TestCase):
    """SoftDeletedRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SoftDeletedRsp:
        """Test SoftDeletedRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SoftDeletedRsp`
        """
        model = SoftDeletedRsp()
        if include_optional:
            return SoftDeletedRsp(
                deleted_key = ''
            )
        else:
            return SoftDeletedRsp(
                deleted_key = '',
        )
        """

    def testSoftDeletedRsp(self):
        """Test SoftDeletedRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
