# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.uuuuc9932bea1f007b34d507c4c4c680b4a7 import UUUUc9932bea1f007b34d507c4c4c680b4a7

class TestUUUUc9932bea1f007b34d507c4c4c680b4a7(unittest.TestCase):
    """UUUUc9932bea1f007b34d507c4c4c680b4a7 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UUUUc9932bea1f007b34d507c4c4c680b4a7:
        """Test UUUUc9932bea1f007b34d507c4c4c680b4a7
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UUUUc9932bea1f007b34d507c4c4c680b4a7`
        """
        model = UUUUc9932bea1f007b34d507c4c4c680b4a7()
        if include_optional:
            return UUUUc9932bea1f007b34d507c4c4c680b4a7(
                total = 56,
                page = 56,
                count_per_page = 56,
                objects = [
                    null
                    ]
            )
        else:
            return UUUUc9932bea1f007b34d507c4c4c680b4a7(
                total = 56,
                page = 56,
                count_per_page = 56,
                objects = [
                    null
                    ],
        )
        """

    def testUUUUc9932bea1f007b34d507c4c4c680b4a7(self):
        """Test UUUUc9932bea1f007b34d507c4c4c680b4a7"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
