# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747269724+a7f6527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_view_models_rsp import SuccRspViewModelsRsp

class TestSuccRspViewModelsRsp(unittest.TestCase):
    """SuccRspViewModelsRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspViewModelsRsp:
        """Test SuccRspViewModelsRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspViewModelsRsp`
        """
        model = SuccRspViewModelsRsp()
        if include_optional:
            return SuccRspViewModelsRsp(
                status = 'ok',
                data = openapi_client.models.view_models_rsp.ViewModelsRsp(
                    object_type = 'model', 
                    id = 56, 
                    short_id = '', 
                    name = '', 
                    env = '', 
                    share_info = [
                        openapi_client.models.view_model_share_info.ViewModelShareInfo(
                            id = 56, 
                            public = True, )
                        ], 
                    content = null, )
            )
        else:
            return SuccRspViewModelsRsp(
                status = 'ok',
                data = openapi_client.models.view_models_rsp.ViewModelsRsp(
                    object_type = 'model', 
                    id = 56, 
                    short_id = '', 
                    name = '', 
                    env = '', 
                    share_info = [
                        openapi_client.models.view_model_share_info.ViewModelShareInfo(
                            id = 56, 
                            public = True, )
                        ], 
                    content = null, ),
        )
        """

    def testSuccRspViewModelsRsp(self):
        """Test SuccRspViewModelsRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
