# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1750641818+35eeab7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_protobuf_message_req import CreateProtobufMessageReq

class TestCreateProtobufMessageReq(unittest.TestCase):
    """CreateProtobufMessageReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProtobufMessageReq:
        """Test CreateProtobufMessageReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProtobufMessageReq`
        """
        model = CreateProtobufMessageReq()
        if include_optional:
            return CreateProtobufMessageReq(
                object_type = 'experiment.protobuf_message',
                batch_id = '',
                run_id = '',
                logs = [
                    openapi_client.models.data_typing.DataTyping(
                        chain_name = '', 
                        iteration = 56, 
                        data = [
                            { }
                            ], )
                    ]
            )
        else:
            return CreateProtobufMessageReq(
                object_type = 'experiment.protobuf_message',
                batch_id = '',
                run_id = '',
                logs = [
                    openapi_client.models.data_typing.DataTyping(
                        chain_name = '', 
                        iteration = 56, 
                        data = [
                            { }
                            ], )
                    ],
        )
        """

    def testCreateProtobufMessageReq(self):
        """Test CreateProtobufMessageReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
