# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1749691195+1d563f2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_user_info_rsp import SuccRspUserInfoRsp

class TestSuccRspUserInfoRsp(unittest.TestCase):
    """SuccRspUserInfoRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspUserInfoRsp:
        """Test SuccRspUserInfoRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspUserInfoRsp`
        """
        model = SuccRspUserInfoRsp()
        if include_optional:
            return SuccRspUserInfoRsp(
                status = 'ok',
                data = openapi_client.models.user_info_rsp.UserInfoRsp(
                    id = 56, 
                    username = '', 
                    super = True, 
                    roles = [
                        ''
                        ], 
                    is_github_user = True, )
            )
        else:
            return SuccRspUserInfoRsp(
                status = 'ok',
                data = openapi_client.models.user_info_rsp.UserInfoRsp(
                    id = 56, 
                    username = '', 
                    super = True, 
                    roles = [
                        ''
                        ], 
                    is_github_user = True, ),
        )
        """

    def testSuccRspUserInfoRsp(self):
        """Test SuccRspUserInfoRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
