# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747269724+a7f6527
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data3 import Data3

class TestData3(unittest.TestCase):
    """Data3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data3:
        """Test Data3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data3`
        """
        model = Data3()
        if include_optional:
            return Data3(
                object_type = 'model',
                short_id = '',
                name = '',
                model_id = '',
                status = '',
                meta = None,
                n_chains = 56,
                n_variables = 56,
                n_samples = 56,
                sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_on = '',
                input = '',
                output = '',
                share_info = [
                    openapi_client.models.view_model_share_info.ViewModelShareInfo(
                        id = 56, 
                        public = True, )
                    ],
                model_name = '',
                id = 56,
                env = '',
                content = None
            )
        else:
            return Data3(
                object_type = 'model',
                short_id = '',
                name = '',
                model_name = '',
                id = 56,
                env = '',
        )
        """

    def testData3(self):
        """Test Data3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
