# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1749691195+1d563f2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.listing_rsp_data_notification_dict import ListingRspDataNotificationDict

class TestListingRspDataNotificationDict(unittest.TestCase):
    """ListingRspDataNotificationDict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListingRspDataNotificationDict:
        """Test ListingRspDataNotificationDict
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListingRspDataNotificationDict`
        """
        model = ListingRspDataNotificationDict()
        if include_optional:
            return ListingRspDataNotificationDict(
                total = 56,
                page = 56,
                count_per_page = 56,
                objects = [
                    openapi_client.models.notification_dict.NotificationDict(
                        id = 56, 
                        event = '', 
                        title = '', 
                        message = '', 
                        msg_object = '', 
                        msg_verb = '', 
                        created_at = '', 
                        read_at = '', )
                    ]
            )
        else:
            return ListingRspDataNotificationDict(
                total = 56,
                page = 56,
                count_per_page = 56,
                objects = [
                    openapi_client.models.notification_dict.NotificationDict(
                        id = 56, 
                        event = '', 
                        title = '', 
                        message = '', 
                        msg_object = '', 
                        msg_verb = '', 
                        created_at = '', 
                        read_at = '', )
                    ],
        )
        """

    def testListingRspDataNotificationDict(self):
        """Test ListingRspDataNotificationDict"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
