# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.payload1 import Payload1

class TestPayload1(unittest.TestCase):
    """Payload1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Payload1:
        """Test Payload1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Payload1`
        """
        model = Payload1()
        if include_optional:
            return Payload1(
                object_type = 'workflow.analyzer_result',
                batch_id = '',
                run_id = '',
                chain_name = '',
                n_sample = 56,
                stat = {
                    'key' : [
                        null
                        ]
                    },
                content = openapi_client.models.model_content.ModelContent(
                    meta = null, 
                    tree = [
                        openapi_client.models.model_tree_node.ModelTreeNode(
                            name = '', 
                            type = 'file', 
                            children = [
                                openapi_client.models.model_tree_node.ModelTreeNode(
                                    name = '', 
                                    type = 'file', )
                                ], )
                        ], ),
                name = '0',
                version = '',
                description = '',
                status = '',
                lambda_image = True,
                tags = [
                    ''
                    ],
                params = '',
                engine = 'lambda',
                get_response = True,
                cache = True,
                lock_key = '',
                action = '',
                meta = { },
                n_chains = 56,
                n_variables = 56,
                n_samples = 56,
                sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datas = [
                    { }
                    ],
                logs = openapi_client.models.data_typing.DataTyping(
                    iteration = {
                        'key' : [
                            null
                            ]
                        }, 
                    vars = {
                        'key' : {
                            'key' : [
                                null
                                ]
                            }
                        }, ),
                data_id = '',
                experiment_id = '',
                analyzer_id = '',
                analyzer_result = '',
                startup_script = '',
                settings = '',
                data_script = '',
                base64_encoded = True,
                data = '',
                data_uri = '',
                return_code = 56,
                errlines = [
                    ''
                    ],
                result = ''
            )
        else:
            return Payload1(
                object_type = 'workflow.analyzer_result',
                batch_id = '',
                run_id = '',
                chain_name = '',
                n_sample = 56,
                stat = {
                    'key' : [
                        null
                        ]
                    },
                datas = [
                    { }
                    ],
                logs = openapi_client.models.data_typing.DataTyping(
                    iteration = {
                        'key' : [
                            null
                            ]
                        }, 
                    vars = {
                        'key' : {
                            'key' : [
                                null
                                ]
                            }
                        }, ),
                return_code = 56,
                errlines = [
                    ''
                    ],
                result = '',
        )
        """

    def testPayload1(self):
        """Test Payload1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
