# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1749691195+1d563f2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cloud_function_lang import CloudFunctionLang

class TestCloudFunctionLang(unittest.TestCase):
    """CloudFunctionLang unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudFunctionLang(self):
        """Test CloudFunctionLang"""
        # inst = CloudFunctionLang()

if __name__ == '__main__':
    unittest.main()
