# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1750066552+6c4a681
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_any import SuccRspAny

class TestSuccRspAny(unittest.TestCase):
    """SuccRspAny unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspAny:
        """Test SuccRspAny
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspAny`
        """
        model = SuccRspAny()
        if include_optional:
            return SuccRspAny(
                status = 'ok',
                data = None
            )
        else:
            return SuccRspAny(
                status = 'ok',
                data = None,
        )
        """

    def testSuccRspAny(self):
        """Test SuccRspAny"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
