# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747273321+ae9f100
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_get_tokens_rsp import SuccRspGetTokensRsp

class TestSuccRspGetTokensRsp(unittest.TestCase):
    """SuccRspGetTokensRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspGetTokensRsp:
        """Test SuccRspGetTokensRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspGetTokensRsp`
        """
        model = SuccRspGetTokensRsp()
        if include_optional:
            return SuccRspGetTokensRsp(
                status = 'ok',
                data = openapi_client.models.get_tokens_rsp.GetTokensRsp(
                    id = 56, 
                    token = '', 
                    token_name = '', 
                    token_desc = '', 
                    token_expire = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return SuccRspGetTokensRsp(
                status = 'ok',
                data = openapi_client.models.get_tokens_rsp.GetTokensRsp(
                    id = 56, 
                    token = '', 
                    token_name = '', 
                    token_desc = '', 
                    token_expire = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testSuccRspGetTokensRsp(self):
        """Test SuccRspGetTokensRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
