# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.delete_linked_account_req import DeleteLinkedAccountReq

class TestDeleteLinkedAccountReq(unittest.TestCase):
    """DeleteLinkedAccountReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteLinkedAccountReq:
        """Test DeleteLinkedAccountReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteLinkedAccountReq`
        """
        model = DeleteLinkedAccountReq()
        if include_optional:
            return DeleteLinkedAccountReq(
                deleted_key = '',
                accounts = [
                    ''
                    ]
            )
        else:
            return DeleteLinkedAccountReq(
        )
        """

    def testDeleteLinkedAccountReq(self):
        """Test DeleteLinkedAccountReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
