# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747014075+4a4a11e
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_list_branch_rsp import SuccRspListBranchRsp

class TestSuccRspListBranchRsp(unittest.TestCase):
    """SuccRspListBranchRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspListBranchRsp:
        """Test SuccRspListBranchRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspListBranchRsp`
        """
        model = SuccRspListBranchRsp()
        if include_optional:
            return SuccRspListBranchRsp(
                status = 'ok',
                data = openapi_client.models.list_branch_rsp.ListBranchRsp(
                    branches = [
                        ''
                        ], )
            )
        else:
            return SuccRspListBranchRsp(
                status = 'ok',
                data = openapi_client.models.list_branch_rsp.ListBranchRsp(
                    branches = [
                        ''
                        ], ),
        )
        """

    def testSuccRspListBranchRsp(self):
        """Test SuccRspListBranchRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
