# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1749691195+1d563f2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_auth0_login_rsp import SuccRspAuth0LoginRsp

class TestSuccRspAuth0LoginRsp(unittest.TestCase):
    """SuccRspAuth0LoginRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspAuth0LoginRsp:
        """Test SuccRspAuth0LoginRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspAuth0LoginRsp`
        """
        model = SuccRspAuth0LoginRsp()
        if include_optional:
            return SuccRspAuth0LoginRsp(
                status = 'ok',
                data = openapi_client.models.auth0_login_rsp.Auth0LoginRsp(
                    tokens = [
                        ''
                        ], )
            )
        else:
            return SuccRspAuth0LoginRsp(
                status = 'ok',
                data = openapi_client.models.auth0_login_rsp.Auth0LoginRsp(
                    tokens = [
                        ''
                        ], ),
        )
        """

    def testSuccRspAuth0LoginRsp(self):
        """Test SuccRspAuth0LoginRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
