# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_list_repo_files_rsp import SuccRspListRepoFilesRsp

class TestSuccRspListRepoFilesRsp(unittest.TestCase):
    """SuccRspListRepoFilesRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspListRepoFilesRsp:
        """Test SuccRspListRepoFilesRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspListRepoFilesRsp`
        """
        model = SuccRspListRepoFilesRsp()
        if include_optional:
            return SuccRspListRepoFilesRsp(
                status = 'ok',
                data = openapi_client.models.list_repo_files_rsp.ListRepoFilesRsp(
                    tree = [
                        openapi_client.models._folder._Folder(
                            name = '', 
                            type = 'folder', 
                            children = [
                                null
                                ], )
                        ], )
            )
        else:
            return SuccRspListRepoFilesRsp(
                status = 'ok',
                data = openapi_client.models.list_repo_files_rsp.ListRepoFilesRsp(
                    tree = [
                        openapi_client.models._folder._Folder(
                            name = '', 
                            type = 'folder', 
                            children = [
                                null
                                ], )
                        ], ),
        )
        """

    def testSuccRspListRepoFilesRsp(self):
        """Test SuccRspListRepoFilesRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
