# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1746749044+01be288
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.listing_rsp_list_object_rsp import ListingRspListObjectRsp

class TestListingRspListObjectRsp(unittest.TestCase):
    """ListingRspListObjectRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListingRspListObjectRsp:
        """Test ListingRspListObjectRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListingRspListObjectRsp`
        """
        model = ListingRspListObjectRsp()
        if include_optional:
            return ListingRspListObjectRsp(
                status = 'ok',
                data = openapi_client.models.listing_rsp_data[list_object_rsp].ListingRspData[ListObjectRsp](
                    total = 56, 
                    page = 56, 
                    count_per_page = 56, 
                    objects = [
                        openapi_client.models.list_object_rsp.ListObjectRsp(
                            short_id = '', 
                            name = '', 
                            model_id = '', 
                            status = '', 
                            meta = openapi_client.models.meta_model.MetaModel(
                                action = '', 
                                iteration_count = 56, ), 
                            n_chains = 56, 
                            n_variables = 56, 
                            n_samples = 56, 
                            sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            run_on = '', 
                            share_info = [
                                openapi_client.models.share_info_model.ShareInfoModel(
                                    id = 56, 
                                    password = '', 
                                    user_id = '', 
                                    to_user_id = '', )
                                ], 
                            model_name = '', )
                        ], )
            )
        else:
            return ListingRspListObjectRsp(
                status = 'ok',
                data = openapi_client.models.listing_rsp_data[list_object_rsp].ListingRspData[ListObjectRsp](
                    total = 56, 
                    page = 56, 
                    count_per_page = 56, 
                    objects = [
                        openapi_client.models.list_object_rsp.ListObjectRsp(
                            short_id = '', 
                            name = '', 
                            model_id = '', 
                            status = '', 
                            meta = openapi_client.models.meta_model.MetaModel(
                                action = '', 
                                iteration_count = 56, ), 
                            n_chains = 56, 
                            n_variables = 56, 
                            n_samples = 56, 
                            sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            run_on = '', 
                            share_info = [
                                openapi_client.models.share_info_model.ShareInfoModel(
                                    id = 56, 
                                    password = '', 
                                    user_id = '', 
                                    to_user_id = '', )
                                ], 
                            model_name = '', )
                        ], ),
        )
        """

    def testListingRspListObjectRsp(self):
        """Test ListingRspListObjectRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
