# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1751439008+e92a9b7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.view_object import ViewObject

class TestViewObject(unittest.TestCase):
    """ViewObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewObject:
        """Test ViewObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewObject`
        """
        model = ViewObject()
        if include_optional:
            return ViewObject(
                object_type = 'model',
                share_id = '',
                sampledata = True,
                fmt = 'csv',
                cloudwatch_log = True,
                batch_id = '',
                run_id = ''
            )
        else:
            return ViewObject(
        )
        """

    def testViewObject(self):
        """Test ViewObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
