# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.uuuu0bdaccc02abe3e86fd53540d087462d8 import UUUU0bdaccc02abe3e86fd53540d087462d8

class TestUUUU0bdaccc02abe3e86fd53540d087462d8(unittest.TestCase):
    """UUUU0bdaccc02abe3e86fd53540d087462d8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UUUU0bdaccc02abe3e86fd53540d087462d8:
        """Test UUUU0bdaccc02abe3e86fd53540d087462d8
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UUUU0bdaccc02abe3e86fd53540d087462d8`
        """
        model = UUUU0bdaccc02abe3e86fd53540d087462d8()
        if include_optional:
            return UUUU0bdaccc02abe3e86fd53540d087462d8(
                status = 'ok',
                data = None
            )
        else:
            return UUUU0bdaccc02abe3e86fd53540d087462d8(
                status = 'ok',
                data = None,
        )
        """

    def testUUUU0bdaccc02abe3e86fd53540d087462d8(self):
        """Test UUUU0bdaccc02abe3e86fd53540d087462d8"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
