# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1.5b359da
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.delete_model_share import DeleteModelShare

class TestDeleteModelShare(unittest.TestCase):
    """DeleteModelShare unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteModelShare:
        """Test DeleteModelShare
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteModelShare`
        """
        model = DeleteModelShare()
        if include_optional:
            return DeleteModelShare(
                share_id = ''
            )
        else:
            return DeleteModelShare(
                share_id = '',
        )
        """

    def testDeleteModelShare(self):
        """Test DeleteModelShare"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
