# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.folder_children_inner import FolderChildrenInner

class TestFolderChildrenInner(unittest.TestCase):
    """FolderChildrenInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FolderChildrenInner:
        """Test FolderChildrenInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FolderChildrenInner`
        """
        model = FolderChildrenInner()
        if include_optional:
            return FolderChildrenInner(
                name = '',
                type = 'file',
                children = [
                    null
                    ]
            )
        else:
            return FolderChildrenInner(
                name = '',
                children = [
                    null
                    ],
        )
        """

    def testFolderChildrenInner(self):
        """Test FolderChildrenInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
