# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.demo_list_item import DemoListItem

class TestDemoListItem(unittest.TestCase):
    """DemoListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DemoListItem:
        """Test DemoListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DemoListItem`
        """
        model = DemoListItem()
        if include_optional:
            return DemoListItem(
                name = '',
                url = [
                    ''
                    ]
            )
        else:
            return DemoListItem(
                name = '',
                url = [
                    ''
                    ],
        )
        """

    def testDemoListItem(self):
        """Test DemoListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
