# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1746749044+01be288
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_xp import UpdateXP

class TestUpdateXP(unittest.TestCase):
    """UpdateXP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateXP:
        """Test UpdateXP
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateXP`
        """
        model = UpdateXP()
        if include_optional:
            return UpdateXP(
                action = '',
                meta = { },
                name = '',
                version = '',
                description = '',
                status = ''
            )
        else:
            return UpdateXP(
        )
        """

    def testUpdateXP(self):
        """Test UpdateXP"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
