# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1750039604+f780c2d
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_config_rsp import GetConfigRsp

class TestGetConfigRsp(unittest.TestCase):
    """GetConfigRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConfigRsp:
        """Test GetConfigRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConfigRsp`
        """
        model = GetConfigRsp()
        if include_optional:
            return GetConfigRsp(
                run_model_url = ''
            )
        else:
            return GetConfigRsp(
                run_model_url = '',
        )
        """

    def testGetConfigRsp(self):
        """Test GetConfigRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
