# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.data2 import Data2

class TestData2(unittest.TestCase):
    """Data2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data2:
        """Test Data2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data2`
        """
        model = Data2()
        if include_optional:
            return Data2(
                object_type = 'workflow',
                short_id = '',
                name = '',
                model_id = '',
                status = '',
                meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                    github = '', 
                    commit_id = '', 
                    origin_url = '', 
                    fixed_version_url = '', ),
                n_chains = 56,
                n_variables = 56,
                n_samples = 56,
                sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_on = '',
                input = '',
                output = '',
                share_info = [
                    openapi_client.models._share_info_model._ShareInfoModel(
                        id = 56, 
                        password = '', 
                        user_id = '', 
                        short_id = '', 
                        to_user_id = '', )
                    ],
                model_name = '',
                id = 56,
                content = None,
                tags = [
                    ''
                    ],
                lambda_image_url = '',
                lambda_image_name = '',
                require_password = True,
                url = '',
                progress = '',
                message = '',
                logs = [
                    [
                        null
                        ]
                    ],
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                path = '',
                fmt = 'raw',
                data_id = '',
                data_name = ''
            )
        else:
            return Data2(
                object_type = 'workflow',
                short_id = '',
                name = '',
                model_id = '',
                status = '',
                meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                    github = '', 
                    commit_id = '', 
                    origin_url = '', 
                    fixed_version_url = '', ),
                model_name = '',
                id = 56,
                tags = [
                    ''
                    ],
                require_password = True,
                url = '',
                progress = '',
                logs = [
                    [
                        null
                        ]
                    ],
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testData2(self):
        """Test Data2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
