# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.uuuuc9932bea1f007b34d507c4c4c680b4a7_objects_inner import UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner

class TestUUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(unittest.TestCase):
    """UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner:
        """Test UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner`
        """
        model = UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner()
        if include_optional:
            return UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(
                object_type = 'workflow',
                short_id = '',
                name = '',
                model_id = '',
                status = '',
                meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                    github = '', 
                    commit_id = '', 
                    origin_url = '', 
                    fixed_version_url = '', ),
                n_chains = 56,
                n_variables = 56,
                n_samples = 56,
                sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_on = '',
                share_info = [
                    openapi_client.models._share_info_model._ShareInfoModel(
                        id = 56, 
                        password = '', 
                        user_id = '', 
                        short_id = '', 
                        to_user_id = '', )
                    ],
                model_name = '',
                workflow_id = '',
                workflow_name = '',
                id = 56,
                content = None,
                tags = [
                    'anonymous'
                    ],
                lambda_image_url = '',
                lambda_image_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                lang = '',
                code = '',
                token = '',
                user_id = 56,
                object1_id = '',
                object2_id = '',
                description = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                path = '',
                fmt = 'raw',
                data_id = '',
                data_name = '',
                data_fmt = '',
                experiment_id = '',
                experiment_name = '',
                analyzer_id = '',
                analyzer_name = '',
                startup_script = '',
                settings = '',
                data_script = ''
            )
        else:
            return UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(
                object_type = 'workflow',
                short_id = '',
                name = '',
                model_id = '',
                status = '',
                meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                    github = '', 
                    commit_id = '', 
                    origin_url = '', 
                    fixed_version_url = '', ),
                n_chains = 56,
                n_variables = 56,
                n_samples = 56,
                sample_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_on = '',
                model_name = '',
                id = 56,
                tags = [
                    'anonymous'
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                lang = '',
                code = '',
                token = '',
                user_id = 56,
                object1_id = '',
                object2_id = '',
                description = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner(self):
        """Test UUUUc9932bea1f007b34d507c4c4c680b4a7ObjectsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
