# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1746749044+01be288
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.succ_rsp_union_user_info_rsp_get_tokens_rsp import SuccRspUnionUserInfoRspGetTokensRsp

class TestSuccRspUnionUserInfoRspGetTokensRsp(unittest.TestCase):
    """SuccRspUnionUserInfoRspGetTokensRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccRspUnionUserInfoRspGetTokensRsp:
        """Test SuccRspUnionUserInfoRspGetTokensRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccRspUnionUserInfoRspGetTokensRsp`
        """
        model = SuccRspUnionUserInfoRspGetTokensRsp()
        if include_optional:
            return SuccRspUnionUserInfoRspGetTokensRsp(
                status = 'ok',
                data = None
            )
        else:
            return SuccRspUnionUserInfoRspGetTokensRsp(
                status = 'ok',
                data = None,
        )
        """

    def testSuccRspUnionUserInfoRspGetTokensRsp(self):
        """Test SuccRspUnionUserInfoRspGetTokensRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
