# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1.5b359da
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.listing_rsp_list_models_rsp_item import ListingRspListModelsRspItem

class TestListingRspListModelsRspItem(unittest.TestCase):
    """ListingRspListModelsRspItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListingRspListModelsRspItem:
        """Test ListingRspListModelsRspItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListingRspListModelsRspItem`
        """
        model = ListingRspListModelsRspItem()
        if include_optional:
            return ListingRspListModelsRspItem(
                status = 'ok',
                data = openapi_client.models.listing_rsp_data[list_models_rsp_item].ListingRspData[ListModelsRspItem](
                    total = 56, 
                    page = 56, 
                    count_per_page = 56, 
                    objects = [
                        openapi_client.models.list_models_rsp_item.ListModelsRspItem(
                            id = 56, 
                            short_id = '', 
                            name = '', 
                            env = '', 
                            share_info = [
                                openapi_client.models.share_info_model.ShareInfoModel(
                                    id = 56, 
                                    password = '', 
                                    user_id = '', 
                                    to_user_id = '', )
                                ], 
                            content = null, 
                            meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                                github = '', 
                                commit_id = '', ), )
                        ], )
            )
        else:
            return ListingRspListModelsRspItem(
                status = 'ok',
                data = openapi_client.models.listing_rsp_data[list_models_rsp_item].ListingRspData[ListModelsRspItem](
                    total = 56, 
                    page = 56, 
                    count_per_page = 56, 
                    objects = [
                        openapi_client.models.list_models_rsp_item.ListModelsRspItem(
                            id = 56, 
                            short_id = '', 
                            name = '', 
                            env = '', 
                            share_info = [
                                openapi_client.models.share_info_model.ShareInfoModel(
                                    id = 56, 
                                    password = '', 
                                    user_id = '', 
                                    to_user_id = '', )
                                ], 
                            content = null, 
                            meta = openapi_client.models._model_meta_in_rsp._ModelMetaInRsp(
                                github = '', 
                                commit_id = '', ), )
                        ], ),
        )
        """

    def testListingRspListModelsRspItem(self):
        """Test ListingRspListModelsRspItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
