# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_linked_account_rsp import ListLinkedAccountRsp

class TestListLinkedAccountRsp(unittest.TestCase):
    """ListLinkedAccountRsp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListLinkedAccountRsp:
        """Test ListLinkedAccountRsp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListLinkedAccountRsp`
        """
        model = ListLinkedAccountRsp()
        if include_optional:
            return ListLinkedAccountRsp(
                linked_accounts = [
                    openapi_client.models._linked_account_schema._LinkedAccountSchema(
                        account = '', 
                        type = '', )
                    ]
            )
        else:
            return ListLinkedAccountRsp(
                linked_accounts = [
                    openapi_client.models._linked_account_schema._LinkedAccountSchema(
                        account = '', 
                        type = '', )
                    ],
        )
        """

    def testListLinkedAccountRsp(self):
        """Test ListLinkedAccountRsp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
