# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1748588801+717309b
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_callback_req import CreateCallbackReq

class TestCreateCallbackReq(unittest.TestCase):
    """CreateCallbackReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCallbackReq:
        """Test CreateCallbackReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCallbackReq`
        """
        model = CreateCallbackReq()
        if include_optional:
            return CreateCallbackReq(
                object_type = 'callback',
                lang = 'julia',
                gist_id = '',
                single_instance = True
            )
        else:
            return CreateCallbackReq(
                object_type = 'callback',
                lang = 'julia',
                gist_id = '',
        )
        """

    def testCreateCallbackReq(self):
        """Test CreateCallbackReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
