# coding: utf-8

"""
    Coinfer Server API

     This part of document describes the HTTP APIs of the Coinfer cloud.  

    The version of the OpenAPI document: 0.0.1747908096+4dc3eec
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_content import ModelContent

class TestModelContent(unittest.TestCase):
    """ModelContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelContent:
        """Test ModelContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelContent`
        """
        model = ModelContent()
        if include_optional:
            return ModelContent(
                meta = openapi_client.models.model_meta.ModelMeta(
                    project_file = 'Project.toml', 
                    entrance_file = 'main.jl', 
                    entrance_func = 'model', 
                    manifest = 'Manifest.toml', ),
                tree = [
                    openapi_client.models.model_tree_node.ModelTreeNode(
                        name = '', 
                        type = 'file', 
                        content = '', 
                        children = [
                            openapi_client.models.model_tree_node.ModelTreeNode(
                                name = '', 
                                type = 'file', 
                                content = '', )
                            ], )
                    ]
            )
        else:
            return ModelContent(
        )
        """

    def testModelContent(self):
        """Test ModelContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
