/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1749800012+14d5928
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateCallbackReq {
    'objectType': CreateCallbackReqObjectTypeEnum;
    'lang': CreateCallbackReqLangEnum;
    /**
    * code location specification. Can be: 1. GitHub gist: gist:<gist-id>:<entrance-file> 2. GitHub repo: repo:<repo-owner>/<repo-name>:<entrance-file>
    */
    'code': string;
    /**
    * Only allow one instance of this callback to run at a time.
    */
    'singleInstance'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "CreateCallbackReqObjectTypeEnum",
            "format": ""
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "CreateCallbackReqLangEnum",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "singleInstance",
            "baseName": "single_instance",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCallbackReq.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateCallbackReqObjectTypeEnum {
    Callback = 'callback'
}
export enum CreateCallbackReqLangEnum {
    Julia = 'julia',
    Python = 'python'
}

