/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750641818+35eeab7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateNSampleStatReq {
    'objectType': CreateNSampleStatReqObjectTypeEnum;
    'batchId': string;
    'runId': string;
    'chainName': string;
    'nSample': number;
    'stat': { [key: string]: Array<any>; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "CreateNSampleStatReqObjectTypeEnum",
            "format": ""
        },
        {
            "name": "batchId",
            "baseName": "batch_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "runId",
            "baseName": "run_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainName",
            "baseName": "chain_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nSample",
            "baseName": "n_sample",
            "type": "number",
            "format": ""
        },
        {
            "name": "stat",
            "baseName": "stat",
            "type": "{ [key: string]: Array<any>; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateNSampleStatReq.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateNSampleStatReqObjectTypeEnum {
    ExperimentNsampleStat = 'experiment.nsample_stat'
}

