/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747908096+4dc3eec
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExperimentRsp } from '../models/ExperimentRsp';
import { ViewExperimentShareRsp } from '../models/ViewExperimentShareRsp';
import { ViewModelsRsp } from '../models/ViewModelsRsp';
import { HttpFile } from '../http/http';

/**
 * @type Data1
 * Type
 * @export
 */
export type Data1 = ExperimentRsp | ViewExperimentShareRsp | ViewModelsRsp;

/**
* @type Data1Class
* @export
*/
export class Data1Class {
    static readonly discriminator: string | undefined = "objectType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "experiment": "ExperimentRsp",
        "model": "ViewModelsRsp",
        "share": "ViewExperimentShareRsp",
    };
}


