/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750036858+bc6226b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExperimentCloudwatchLogRsp {
    'objectType': ExperimentCloudwatchLogRspObjectTypeEnum;
    'logs': Array<Array<any>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "ExperimentCloudwatchLogRspObjectTypeEnum",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<Array<any>>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExperimentCloudwatchLogRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ExperimentCloudwatchLogRspObjectTypeEnum {
    ExperimentCloudwatchLog = 'experiment.cloudwatch_log'
}

