/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747269724+a7f6527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetConfigRsp {
    'runModelUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "runModelUrl",
            "baseName": "run_model_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetConfigRsp.attributeTypeMap;
    }

    public constructor() {
    }
}
