/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1749449947+cf3022c
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetTokensRsp {
    'id': number;
    'token': string;
    'tokenName': string;
    'tokenDesc': string;
    'tokenExpire': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenName",
            "baseName": "token_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenDesc",
            "baseName": "token_desc",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenExpire",
            "baseName": "token_expire",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return GetTokensRsp.attributeTypeMap;
    }

    public constructor() {
    }
}
