/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747014075+4a4a11e
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelMetaInRsp } from '../models/ModelMetaInRsp';
import { ShareInfoModel } from '../models/ShareInfoModel';
import { HttpFile } from '../http/http';

export class ListModelsRspItem {
    'id': number;
    'shortId': string;
    'name': string;
    'env': string | null;
    'shareInfo'?: Array<ShareInfoModel> | null;
    'content'?: any | null;
    'meta': ModelMetaInRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "shortId",
            "baseName": "short_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "env",
            "baseName": "env",
            "type": "string",
            "format": ""
        },
        {
            "name": "shareInfo",
            "baseName": "share_info",
            "type": "Array<ShareInfoModel>",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "any",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "ModelMetaInRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListModelsRspItem.attributeTypeMap;
    }

    public constructor() {
    }
}
