/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750401329+61147f7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListObjectTmp {
    /**
    * page number
    */
    'pageNo'?: number;
    /**
    * page size
    */
    'pageSize'?: number;
    'objectType': ListObjectTmpObjectTypeEnum;
    /**
    * Whether to return the related share info
    */
    'withShareInfo'?: boolean;
    /**
    * Filter objects shared by the current user
    */
    'sharedByMe'?: boolean;
    /**
    * Filter objects shared with the current user
    */
    'sharedWithMe'?: boolean;
    'modelIds'?: Array<string>;
    'status'?: ListObjectTmpStatusEnum;
    'runOn'?: ListObjectTmpRunOnEnum;
    'hasModel'?: ListObjectTmpHasModelEnum;
    'kind'?: ListObjectTmpKindEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pageNo",
            "baseName": "page_no",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "ListObjectTmpObjectTypeEnum",
            "format": ""
        },
        {
            "name": "withShareInfo",
            "baseName": "with_share_info",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharedByMe",
            "baseName": "shared_by_me",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharedWithMe",
            "baseName": "shared_with_me",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modelIds",
            "baseName": "model_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ListObjectTmpStatusEnum",
            "format": ""
        },
        {
            "name": "runOn",
            "baseName": "run_on",
            "type": "ListObjectTmpRunOnEnum",
            "format": ""
        },
        {
            "name": "hasModel",
            "baseName": "has_model",
            "type": "ListObjectTmpHasModelEnum",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "ListObjectTmpKindEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListObjectTmp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ListObjectTmpObjectTypeEnum {
    Model = 'model',
    Experiment = 'experiment',
    Share = 'share',
    Event = 'event',
    Callback = 'callback',
    Relation = 'relation',
    Empty = ''
}
export enum ListObjectTmpStatusEnum {
    New = 'NEW',
    Run = 'RUN',
    Fin = 'FIN',
    Err = 'ERR',
    Empty = ''
}
export enum ListObjectTmpRunOnEnum {
    Lambda = 'Lambda',
    Fargate = 'Fargate',
    Local = 'Local',
    Empty = ''
}
export enum ListObjectTmpHasModelEnum {
    True = 'true',
    False = 'false',
    Empty = ''
}
export enum ListObjectTmpKindEnum {
    Model = 'model',
    Script = 'script'
}

