/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1749800012+14d5928
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListExperiment {
    /**
    * page number
    */
    'pageNo'?: number;
    /**
    * page size
    */
    'pageSize'?: number;
    'objectType': ListExperimentObjectTypeEnum;
    /**
    * Whether to return the related share info
    */
    'withShareInfo'?: boolean;
    /**
    * Filter objects shared by the current user
    */
    'sharedByMe'?: boolean;
    /**
    * Filter objects shared with the current user
    */
    'sharedWithMe'?: boolean;
    'status'?: ListExperimentStatusEnum;
    'runOn'?: ListExperimentRunOnEnum;
    'hasModel'?: ListExperimentHasModelEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pageNo",
            "baseName": "page_no",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "ListExperimentObjectTypeEnum",
            "format": ""
        },
        {
            "name": "withShareInfo",
            "baseName": "with_share_info",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharedByMe",
            "baseName": "shared_by_me",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharedWithMe",
            "baseName": "shared_with_me",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ListExperimentStatusEnum",
            "format": ""
        },
        {
            "name": "runOn",
            "baseName": "run_on",
            "type": "ListExperimentRunOnEnum",
            "format": ""
        },
        {
            "name": "hasModel",
            "baseName": "has_model",
            "type": "ListExperimentHasModelEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListExperiment.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ListExperimentObjectTypeEnum {
    Experiment = 'experiment'
}
export enum ListExperimentStatusEnum {
    New = 'NEW',
    Run = 'RUN',
    Fin = 'FIN',
    Err = 'ERR',
    Empty = ''
}
export enum ListExperimentRunOnEnum {
    Lambda = 'Lambda',
    Fargate = 'Fargate',
    Local = 'Local',
    Empty = ''
}
export enum ListExperimentHasModelEnum {
    True = 'true',
    False = 'false',
    Empty = ''
}

