/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747014075+4a4a11e
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner } from '../models/ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner';
import { HttpFile } from '../http/http';

export class ListingRspDataUnionListExperimentRspListModelsRspItem {
    'total': number;
    'page': number;
    'countPerPage': number;
    'objects': Array<ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "countPerPage",
            "baseName": "count_per_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<ListingRspDataUnionListExperimentRspListModelsRspItemObjectsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListingRspDataUnionListExperimentRspListModelsRspItem.attributeTypeMap;
    }

    public constructor() {
    }
}
