/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747269724+a7f6527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModifyCurrentUserNew {
    'type'?: ModifyCurrentUserNewTypeEnum;
    'newPassword'?: string | null;
    'password'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ModifyCurrentUserNewTypeEnum",
            "format": ""
        },
        {
            "name": "newPassword",
            "baseName": "new_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModifyCurrentUserNew.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ModifyCurrentUserNewTypeEnum {
    UpdateUser = 'update_user'
}

