/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747269724+a7f6527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateExperiment } from '../models/UpdateExperiment';
import { UpdateModel } from '../models/UpdateModel';
import { HttpFile } from '../http/http';

/**
 * @type Payload2
 * Type
 * @export
 */
export type Payload2 = UpdateExperiment | UpdateModel;

/**
* @type Payload2Class
* @export
*/
export class Payload2Class {
    static readonly discriminator: string | undefined = "objectType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "experiment": "UpdateExperiment",
        "model": "UpdateModel",
    };
}

