/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1749800012+14d5928
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateCallbackReq } from '../models/CreateCallbackReq';
import { CreateEventReq } from '../models/CreateEventReq';
import { CreateExperiment } from '../models/CreateExperiment';
import { CreateExperimentShare } from '../models/CreateExperimentShare';
import { CreateModel } from '../models/CreateModel';
import { CreateRelationReq } from '../models/CreateRelationReq';
import { HttpFile } from '../http/http';

/**
 * @type Payload1
 * Type
 * @export
 */
export type Payload1 = CreateCallbackReq | CreateEventReq | CreateExperiment | CreateExperimentShare | CreateModel | CreateRelationReq;

/**
* @type Payload1Class
* @export
*/
export class Payload1Class {
    static readonly discriminator: string | undefined = "objectType";

    static readonly mapping: {[index: string]: string} | undefined = {
        "callback": "CreateCallbackReq",
        "event": "CreateEventReq",
        "experiment": "CreateExperiment",
        "model": "CreateModel",
        "relation": "CreateRelationReq",
        "share": "CreateExperimentShare",
    };
}





