/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1746749044+01be288
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetModelShareRsp } from '../models/GetModelShareRsp';
import { HttpFile } from '../http/http';

export class SuccRspGetModelShareRsp {
    'status': SuccRspGetModelShareRspStatusEnum;
    'data': GetModelShareRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspGetModelShareRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetModelShareRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspGetModelShareRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspGetModelShareRspStatusEnum {
    Ok = 'ok'
}

