/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747014075+4a4a11e
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ViewModelsRsp } from '../models/ViewModelsRsp';
import { HttpFile } from '../http/http';

export class SuccRspViewModelsRsp {
    'status': SuccRspViewModelsRspStatusEnum;
    'data': ViewModelsRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspViewModelsRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ViewModelsRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspViewModelsRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspViewModelsRspStatusEnum {
    Ok = 'ok'
}

