/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1749800012+14d5928
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Auth0ConfigRsp } from '../models/Auth0ConfigRsp';
import { HttpFile } from '../http/http';

export class SuccRspAuth0ConfigRsp {
    'status': SuccRspAuth0ConfigRspStatusEnum;
    'data': Auth0ConfigRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspAuth0ConfigRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Auth0ConfigRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspAuth0ConfigRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspAuth0ConfigRspStatusEnum {
    Ok = 'ok'
}

