/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1747269724+a7f6527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Data1 } from '../models/Data1';
import { HttpFile } from '../http/http';

export class SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp {
    'status': SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRspStatusEnum;
    'data': Data1;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Data1",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspUnionExperimentRspListModelsRspItemCreateExperimentShareRspStatusEnum {
    Ok = 'ok'
}

