/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1748513902+521f943
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserLoginRsp } from '../models/UserLoginRsp';
import { HttpFile } from '../http/http';

export class SuccRspUserLoginRsp {
    'status': SuccRspUserLoginRspStatusEnum;
    'data': UserLoginRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspUserLoginRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "UserLoginRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspUserLoginRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspUserLoginRspStatusEnum {
    Ok = 'ok'
}

