/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750036858+bc6226b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetConfigRsp } from '../models/GetConfigRsp';
import { HttpFile } from '../http/http';

export class SuccRspGetConfigRsp {
    'status': SuccRspGetConfigRspStatusEnum;
    'data': GetConfigRsp;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "SuccRspGetConfigRspStatusEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetConfigRsp",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccRspGetConfigRsp.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SuccRspGetConfigRspStatusEnum {
    Ok = 'ok'
}

