/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750036858+bc6226b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateEventReq {
    'objectType': UpdateEventReqObjectTypeEnum;
    'params'?: string;
    'engine'?: UpdateEventReqEngineEnum;
    'lockKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "UpdateEventReqObjectTypeEnum",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "string",
            "format": ""
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "UpdateEventReqEngineEnum",
            "format": ""
        },
        {
            "name": "lockKey",
            "baseName": "lock_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateEventReq.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateEventReqObjectTypeEnum {
    Event = 'event'
}
export enum UpdateEventReqEngineEnum {
    Lambda = 'lambda',
    Fargate = 'fargate'
}

