/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1746749044+01be288
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Payload2 } from '../models/Payload2';
import { HttpFile } from '../http/http';

export class UpdateObject {
    'payload': Payload2;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Payload2",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateObject.attributeTypeMap;
    }

    public constructor() {
    }
}
