/**
 * Coinfer Server API
 *  This part of document describes the HTTP APIs of the Coinfer cloud.  
 *
 * OpenAPI spec version: 0.0.1750036858+bc6226b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ViewObject } from '../models/ViewObject';
import { HttpFile } from '../http/http';

export class ViewObjectTmp {
    'payload': ViewObject;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "ViewObject",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ViewObjectTmp.attributeTypeMap;
    }

    public constructor() {
    }
}
